pipeline:
  name: Karate Test Pipeline
  identifier: Build_karate_master_1739724526924
  projectIdentifier: default_project
  orgIdentifier: default
  stages:
    - stage:
        name: Run tests
        identifier: Run_tests
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Arm64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: RunTests
                  name: RunTests_1
                  identifier: RunTests_1
                  spec:
                    language: Java
                    buildTool: Maven
                    args: clean test
                    runOnlySelectedTests: true
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - target/surefire-reports/TEST-examples.ExamplesTest.xml
                    enableTestSplitting: false
  properties:
    ci:
      codebase:
        connectorRef: GitHubKarate
        repoName: karate-master
        build: <+input>
