pipeline:
  name: Karate Test Pipeline
  identifier: Build_karate_master_1739724526924
  projectIdentifier: default_project
  orgIdentifier: default
  stages:
    - stage:
        name: test
        identifier: test
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Arm64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Bash
                    command: mvn test -Dkarate.options=--env ${karate.env}
  properties:
    ci:
      codebase:
        connectorRef: GitHubKarate
        repoName: karate-master
        build: <+input>
  variables:
    - name: env
      type: String
      description: ""
      required: true
      value: <+input>
