kind: pipeline
spec:
  stages:
  - type: ci
    spec:
      steps:
      - name: test
        type: run
        spec:
          container: maven:3.8-openjdk-17
          script: |-
            mvn test
        reports:
        - name: test-results
          path: target/"target/cucumber-html-reports/**/*"