pipeline:
  name: Karate Test Pipeline
  identifier: Build_karate_master_1739724526924
  projectIdentifier: default_project
  orgIdentifier: default
  stages:
    - type: ci
      spec:
        steps:
          - name: test
            type: run
            spec:
              container: maven:3.8-openjdk-17
              script: mvn test -Dkarate.options=--env ${karate.env}
            reports:
              - name: test-results
                path: target/"target/cucumber-html-reports/**/*"
  properties:
    ci:
      codebase:
        connectorRef: GitHubKarate
        repoName: karate-master
        build: <+input>
  variables:
    - name: env
      type: String
      description: ""
      required: true
      value: <+input>
