pipeline:
  identifier: Build_karate_master_1739724526924
  name: Build karate-master
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: GitHubKarate
        repoName: karate-master
  parameters:
    - name: karate.env
      type: string
      default: dev
    - name: tags
      type: string
      default: ""
  stages:
    - type: ci
      spec:
        steps:
          - name: test
            type: run
            spec:
              script: |
                docker run -it --rm -v "$(pwd)":/src -w /src -v "$HOME/.m2":/root/.m2 maven:3-amazoncorretto-17 mvn clean test -Dkarate.env=${karate.env} -Dtags=${tags}
            reports:
              - name: test-results
                path: target/"target/cucumber-html-reports/**/*"