pipeline:
  identifier: karate_test_pipeline
  name: Karate Test Pipeline
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: GitHubKarate
        repoName: karate-master
  inputVariables:
    - name: environment
      type: String
      description: "Environment to run tests against (dev/qa/staging/prod)"
      required: true
  tags: {}
  stages:
    - stage:
        identifier: build_and_test
        name: Build and Test
        spec:
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.DockerHub
              image: maven:3.8-jdk-17
          execution:
            steps:
              - step:
                  identifier: maven_test
                  name: Run Maven Tests
                  spec:
                    command: |-
                      mvn clean test
                  timeout: 10m
                  type: Run
        type: CI
