pipeline:
  name: Karate Test Pipeline
  identifier: karate_test_pipeline
  projectIdentifier: default_project
  orgIdentifier: default
  properties:
    ci:
      codebase:
        connectorRef: GitHubKarate
        repoName: karate-master
        build: <+input>
        branch: main  # or your default branch name
  inputVariables:
    - name: environment
      type: String
      description: "Environment to run tests against (dev/qa/staging/prod)"
      required: true
  tags: {}
  stages:
    - stage:
        name: Run Karate Tests
        identifier: Run_Karate_Tests
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Set Environment
                  identifier: Set_Environment
                  spec:
                    shell: Sh
                    command: |-
                      # Set default environment if not specified
                      export KARATE_ENV=${KARATE_ENV:-dev}
                      export API_BASE_URL=${API_BASE_URL:-https://dev-api.example.com}
                      echo "Running tests for environment: $KARATE_ENV"
                      echo "API Base URL: $API_BASE_URL"
              - step:
                  type: Run
                  name: Run Tests
                  identifier: Run_Tests
                  spec:
                    shell: Sh
                    image: maven:3.8-jdk-17
                    command: mvn test -DKARATE_ENV=${KARATE_ENV} -DAPI_BASE_URL=${API_BASE_URL}
              - step:
                  type: Run
                  name: Save Reports
                  identifier: Save_Reports
                  spec:
                    shell: Sh
                    command: |-
                      if [ -d "target/cucumber-html-reports" ]; then
                        echo "Cucumber reports generated successfully"
                        ls -la target/cucumber-html-reports/
                      else
                        echo "No Cucumber reports found"
                      fi
