pipeline:
  identifier: Build_karate_master_1739724526924
  name: Build karate-master
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: GitHubKarate
        repoName: karate-master
  parameters:
    - name: karate.env
      type: string
      default: dev
    - name: tags
      type: string
      default: ""
  stages:
    - type: ci
      spec:
        steps:
          - name: test
            type: run
            spec:
              container: maven:3.8-openjdk-17
              script: mvn test -Dkarate.env=${{karate.env}} -Dtags=${{tags}}
            reports:
              - name: test-results
                path: target/"target/cucumber-html-reports/**/*"
    - stage:
        name: env-varibale
        identifier: envvaribale
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: RunTests
                  name: RunTests_1
                  identifier: RunTests_1
                  spec:
                    language: Java
                    buildTool: Maven
                    args: " mvn test -Dkarate.env=${{karate.env}} -Dtags=${{tags}}"
                    runOnlySelectedTests: true
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - target/"target/cucumber-html-reports/**/*"
                    enableTestSplitting: false
